apply plugin: 'com.android.application'

android {
    namespace "com.appknox.mfva"
    compileSdk 34
    defaultConfig {
        applicationId "com.appknox.mfva"
        minSdkVersion 23
        targetSdkVersion 26
        versionCode 8
        versionName "1.1.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        release {
            storeFile file("${System.properties['user.home']}/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }
    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        buildConfig true
    }
    lint {
        abortOnError false
    }
}
dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    api 'com.android.support:appcompat-v7:26.1.0'
    api 'com.android.support.constraint:constraint-layout:1.0.2'
    api 'com.android.support:design:26.1.0'
    api 'com.squareup.okhttp3:okhttp:3.8.0'
    testImplementation 'junit:junit:4.12'
}
