package com.appknox.mfva;


import android.os.Bundle;
import android.util.Log;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;

import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.KeyStore;

import javax.crypto.Cipher;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;



public class ExportedActivity extends SecureBaseActivity {

    private static final String AES_TRANSFORMATION = "AES/GCM/NoPadding";
    private static final String KEY_ALIAS = "secure_app_key";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_exported);



        try {
            // Generate or retrieve a secure AES key from Android Keystore
            SecretKey secureKey = getOrCreateSecretKey();

            // Instantiate Cipher with AES/GCM/NoPadding
            Cipher cipher = Cipher.getInstance(AES_TRANSFORMATION);
            // Initialize cipher for encryption or decryption with the secureKey
            // For encryption, a new IV will be generated by the cipher.
            // For decryption, the IV used during encryption must be provided.
            // cipher.init(Cipher.ENCRYPT_MODE, secureKey);
            // byte[] encryptedData = cipher.doFinal(plaintext);
            // byte[] iv = cipher.getIV();

        } catch (Exception e) {
            // Handle cryptographic exceptions appropriately
            e.printStackTrace();
        }
    }

    private SecretKey getOrCreateSecretKey() throws Exception {
        KeyStore keyStore = KeyStore.getInstance("AndroidKeyStore");
        keyStore.load(null);

        if (!keyStore.containsAlias(KEY_ALIAS)) {
            KeyGenerator keyGenerator = KeyGenerator.getInstance(
                    KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore");
            keyGenerator.init(new KeyGenParameterSpec.Builder(KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).setRandomizedEncryptionRequired(true).build());
            return keyGenerator.generateKey();
        } else {
            KeyStore.SecretKeyEntry secretKeyEntry = (KeyStore.SecretKeyEntry) keyStore.getEntry(KEY_ALIAS, null);
            return secretKeyEntry.getSecretKey();
        }
    }
}
